/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:059363b6-5190-4586-b25c-32ad5600150c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_VZKqFXIps",
    "aws_user_pools_web_client_id": "79fdiq3v94jrv24dfuh100p7f4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dcclywyarrdepcwvfzjpawvn2u.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yglz7iw6x5cfliqqtpjdcds4te",
    "aws_user_files_s3_bucket": "first-s3-bucket154428-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
