/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:059363b6-5190-4586-b25c-32ad5600150c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_VZKqFXIps",
    "aws_user_pools_web_client_id": "79fdiq3v94jrv24dfuh100p7f4",
    "oauth": {}
};


export default awsmobile;
